version: "3.3"

services:
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: app_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: 123456

  frontend:
    container_name: app_front
    build: frontend
    restart: always
    ports:
      - 3000:80

  backend:
    container_name: app_backend
    build: ./backend
    restart: always
    command: ["sh", "-c", "sleep 10"]
    ports:
      - 8080:8080
    depends_on:
      - mysql
